# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ваш емейл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Общие вопросы', 'Общие вопросы'), ('Зарплата и социальный пакет', 'Зарплата и социальный пакет')], default='', max_length=40, verbose_name='Категория вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ваше имя'),
        ),
    ]
