# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180117_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('general', 'Общие вопросы'), ('salary', 'Зарплата и социальный пакет')], default='', max_length=40, verbose_name='Категория вопроса'),
        ),
    ]
