# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('text', models.TextField(verbose_name='Содержимое новости')),
                ('image', models.ImageField(blank=True, upload_to='uploads/news/images/', verbose_name='Картинка новости')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('hidden', 'Скрыто')], default='published', max_length=20, verbose_name='Статус')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
