# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/user_resume/photo/')),
                ('industry', models.CharField(choices=[('E-commerce', 'E-commerce'), ('Авиация', 'Авиация')], max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('resume_file', models.FileField(upload_to='uploads/user_resume/')),
                ('skills', models.TextField(blank=True)),
                ('experience', models.CharField(choices=[('до 1 года', 'до 1 года'), ('от 1-3 лет', 'от 1-3 лет'), ('от 3-5 лет', 'от 3-5 лет'), ('более 5 лет', 'более 5 лет')], max_length=20)),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('hidden', 'Скрыто')], default='published', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
