# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(choices=[('до 1 года', 'до 1 года'), ('от 1-3 лет', 'от 1-3 лет'), ('от 3-5 лет', 'от 3-5 лет'), ('более 5 лет', 'более 5 лет')], max_length=20, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='industry',
            field=models.CharField(choices=[('E-commerce', 'E-commerce'), ('Авиация', 'Авиация')], max_length=100, verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место поиска работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/user_resume/photo/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='uploads/user_resume/', verbose_name='Файл резюме'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('hidden', 'Скрыто')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Саммари'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок резюме'),
        ),
    ]
