# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('for_role', models.CharField(choices=[('all', 'Для всех'), ('users', 'Пользователям'), ('companies', 'Рекрутёрам')], default='all', max_length=40, verbose_name='Для кого')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('section_content', models.TextField(verbose_name='Содержимое раздела')),
                ('visibility', models.CharField(choices=[('show', 'Пользователь видит раздел в списке разделов курса'), ('hide', 'Пользователь получает доступ к разделу только по ссылке')], default='show', max_length=40, verbose_name='Видимость раздела')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок перед формой')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст перед формой')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSection')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('progress_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseSection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/homework/', verbose_name='Файл с домашним заданием')),
                ('status', models.CharField(choices=[('send', 'Пользователь отправил файл'), ('review', 'Файл проверен куратором')], default='send', max_length=40, verbose_name='Статус')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
