# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('company_site', models.CharField(max_length=100, verbose_name='Сайт компании')),
                ('company_logo', models.ImageField(blank=True, upload_to='uploads/companies/photo/', verbose_name='Лого компании')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок вакансии')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местоположение')),
                ('type', models.CharField(choices=[('Удаленная', 'Удаленная'), ('Постоянная', 'Постоянная'), ('Проектная', 'Проектная')], max_length=100, verbose_name='Тип вакансии')),
                ('email_for_resume', models.EmailField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('company_site', models.CharField(max_length=100, verbose_name='Сайт компании')),
                ('company_logo', models.ImageField(blank=True, upload_to='uploads/companies/photo/', verbose_name='Лого компании')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('hidden', 'Скрыто')], default='published', max_length=20, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
