# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180211_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
